# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34919ddfae8e4935bfab1526c5b024a177b55dfa54d6aba76c0aeea48562c20ded66e5f6f23bd7ab7d5c387f1ad4deef2262227de138a266f4cd5a0e8faea5df

test:
  secret_key_base: 7f69203a2d509cd6cf84770cc8c0565549f94a751c2a0da1df69a1757daa18e711566407e7d198d20efe016ec635fed0f6e6cf0cd454f4ae75288804738f5031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
